@startuml

class Juego
class Jugador
class IA
class Moto
class Tron
class Arena
class Oponente
class Muro
class Jet
class Estela
class Colisionable

Moto o-- Arena
Tron o-- Moto
Oponente o-- Moto

Jugador O-- Tron
IA o-- Oponente

Moto *-- Estela
Arena *-- Muro
Arena *-- Jet

Colisionable --|> Muro
Colisionable --|> Moto
Colisionable --|> Jet
Colisionable --|> Estela

@enduml